name: Deploy Web App to GitHub Pages (Wasm)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4

    - name: ☕ Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: 🔧 Grant Executable Permissions to Gradlew
      run: chmod +x gradlew

    - name: 🌐 Build Wasm WebApp
      run: ./gradlew :composeApp:wasmJsBrowserDistribution

    - name: 🛠️ Setup Pages
      uses: actions/configure-pages@v4

    - name: 📦 Upload Web Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'composeApp/build/dist/wasmJs/productionExecutable/'

    - name: 🚀 Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
